### ISSUE TITLE
💡 [REQUEST] - ResourceQuota

### ISSUE THREAD

**Issue by Baboulinet-33** [cloud-pi-native/console#1420]
### Description

Actuellement seul le CPU et la RAM sont limités par un ResourceQuota.

L'idée serait d'ajouter plusieurs limites (voir de pouvoir les manager dans la console par un administrateur par projet :) ):
- Limiter la taille totale des PVC pour qu'un projet ne consomme pas trop (5Gi dans l'exemple)
- Interdire au projet d'avoir des services de type NodePort
- Limiter le nombre de GPU pour un projet: requête pour plus tard

```yaml
apiVersion: v1
kind: ResourceQuota
metadata:
  labels:
    app.kubernetes.io/managed-by: dso-console
  name: dso-quota
spec:
  hard:
    requests.storage: "5Gi"
    services.nodeports: 0
    requests.nvidia.com/gpu: 4
```

### Définition du fini

- [ ] La fonctionnalité est terminée
- [ ] Les tests liés à cette fonctionnalité ont été ajoutés
- [ ] La documentation liée à cette fonctionnalité a été ajoutée (cf. https://github.com/cloud-pi-native/documentation)
- [ ] La communication avec les autres équipes impliquées par cette fonctionnalité a été faite
